version: "3.8"
services:
  pokedex:
    container_name: pokedex
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - /app/.next
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network
networks:
  my_network:
    external: true
volumes:
  node_modules:
