export const colorTypes = {
  feu: "bg-[#E72324]",
  eau: "bg-[#2481EF]",
  plante: "bg-[#3da224]",
  électrik: "bg-[#FAC100]",
  sol: "bg-[#92501B]",
  roche: "bg-[#b0aa82]",
  fée: "bg-[#EF70EF]",
  poison: "bg-[#923FCC]",
  insecte: "bg-[#92A212]",
  dragon: "bg-[#4F60E2]",
  psy: "bg-[#ef3f7a]",
  vol: "bg-[#82BAEF]",
  combat: "bg-[#FF8100]",
  normal: "bg-[#A0A2A0]",
  spectre: "bg-[#703F70]",
  glace: "bg-[#3DD9FF]",
  ténèbres: "bg-[#4F3F3D]",
  acier: "bg-[#60A2B9]",
};

export const backgroundColorTypes = {
  feu: "bg-[#FDDCD5]",
  eau: "bg-[#D7EBFF]",
  plante: "bg-[#E4F5DC]",
  électrik: "bg-[#FFF3D5]",
  sol: "bg-[#F6F0DE]",
  roche: "bg-[#F1EDDE]",
  fée: "bg-[#F8EAF9]",
  poison: "bg-[#F0DEED]",
  insecte: "bg-[#EEF1D2]",
  dragon: "bg-[#E7DDFD]",
  psy: "bg-[#FFE3ED]",
  vol: "bg-[#EBEEFD]",
  combat: "bg-[#FFEDDD]",
  normal: "bg-[#EEEDE9]",
  spectre: "bg-[#F7E1F7]",
  glace: "bg-[#DEF5FA]",
  ténèbres: "bg-[#E3DEDA]",
  acier: "bg-[#EEEEF3]",
};

export const effectivenessBackgroundColor: { [key: string]: string } = {
  "0x": "bg-[#CCCCCC]",
  "0.25x": "bg-[#3AF24B]",
  "0.5x": "bg-[#AAFFAA]",
  "1x": "bg-[#FFFFAA]",
  "2x": "bg-[#FFAAAA]",
  "4x": "bg-[#FF5555]",
};
